channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.10.0=py37_0
  - aiohttp=3.6.3=py37h7b6447c_0
  - astroid=2.4.2=py37_0
  - async-timeout=3.0.1=py37_0
  - attrs=20.2.0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cryptography=3.1.1=py37h1ba5d50_0
  - cuda80=1.0=h205658b_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37hb892b2f_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - google-auth=1.22.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - isort=5.6.4=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.2=py37_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.6=py37h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=py37hfd86e86_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.0=py37h9a89aac_0
  - pip=20.2.4=py37_0
  - protobuf=3.13.0.1=py37he6710b0_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycocotools=2.0.2=py37h8f50634_1
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py37_0
  - pylint=2.6.0=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=cuda100py37h53c1284_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorboardx=2.1=py_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.1=py_0
  - torchvision=0.4.2=cuda100py37hecfc37a_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.50.2=py_0
  - typed-ast=1.4.1=py37h7b6447c_0
  - urllib3=1.25.10=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.35.1=py_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.2=py37h7b6447c_0
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
      - autopep8==1.5.4
      - pycodestyle==2.6.0
